name: 'Tag new version'

on:
  workflow_call:
    secrets:
      deploy_key:
        required: true
        description: 'Create a Deploy Key and pass a private key here, so the push of the tag will trigger the builds, based on it.'

permissions:
  contents: write

jobs:
  new-tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.deploy_key }}

      - name: Conventional Changelog Action
        id: tag-changelog
        uses: TriPSs/conventional-changelog-action@v4
        with:
          github-token: ''
          git-user-name: 'Release Action'
          git-user-email: 'release-action@github.actions.com'
          preset: 'conventionalcommits'
          skip-git-pull: 'true'
          output-file: 'false'
          skip-version-file: 'true'
          skip-commit: 'true'

      - name: Prepare draft of release
        if: steps.tag-changelog.outputs.skipped != 'true'
        run: |
          gh release create ${{ steps.tag-changelog.outputs.tag }} --draft -n "${{ steps.tag-changelog.outputs.clean_changelog }}" -t "Release ${{ steps.tag-changelog.outputs.tag }}"
        env:
          GH_TOKEN: ${{ github.token }}
